{% set name = "simpleeval" %}
{% set version = "0.9.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a30f9cc01825fe4c719c785e3762623e350c4840d5e6855c2a8496baaa65fac

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - simpleeval
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/danthedeckie/simpleeval
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: A simple, safe single expression evaluator library.
  description: |
    A quick single file library for easily adding evaluatable expressions
    into python projects, or if you want to allow simple formulae in a
    web application, but don’t want to give full eval() access.
  doc_url: https://github.com/danthedeckie/simpleeval/blob/master/README.rst
  dev_url: https://github.com/danthedeckie/simpleeval

extra:
  recipe-maintainers:
    - mtekman
    - bgruening
