{% set name = "simpleeval" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67bbf246040ac3b57c29cf048657b9cf31d4e7b9d6659684daa08ca8f1e45829

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=2.5, !=3.0.*, !=3.1.*, !=3.2.*
    - pip
  run:
    - python >=2.5, !=3.0.*, !=3.1.*, !=3.2.*

test:
  imports:
    - simpleeval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danthedeckie/simpleeval
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: A simple, safe single expression evaluator library.
  description: |
    A quick single file library for easily adding evaluatable expressions
    into python projects, or if you want to allow simple formulae in a
    web application, but don’t want to give full eval() access.
  doc_url: https://github.com/danthedeckie/simpleeval/blob/master/README.rst
  dev_url: https://github.com/danthedeckie/simpleeval

extra:
  recipe-maintainers:
    - mtekman
    - bgruening
