{% set name = "simpleeval" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b95f8b04d35cf1f793749fc3034d332dafb20e71fadf56631b4642fcc84a26a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=2.5, !=3.0.*, !=3.1.*, !=3.2.*
    - pip
  run:
    - python >=2.5, !=3.0.*, !=3.1.*, !=3.2.*

test:
  imports:
    - simpleeval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danthedeckie/simpleeval
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: A simple, safe single expression evaluator library.
  description: |
    A quick single file library for easily adding evaluatable expressions
    into python projects, or if you want to allow simple formulae in a
    web application, but don’t want to give full eval() access.
  doc_url: https://github.com/danthedeckie/simpleeval/blob/master/README.rst
  dev_url: https://github.com/danthedeckie/simpleeval

extra:
  recipe-maintainers:
    - mtekman
    - bgruening
